/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author navis
 */
public class Reports extends javax.swing.JFrame {

    /**
     * Creates new form ReportGernerator
     */
    public Reports() {
        initComponents();
        dtePickerFrom.setDate(java.sql.Date.valueOf(LocalDate.now()));
        dtePickerTo.setDate(java.sql.Date.valueOf(LocalDate.now()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtePickerTo = new org.jdesktop.swingx.JXDatePicker();
        dtePickerFrom = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnTelephone = new javax.swing.JButton();
        btnChef = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReportArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(dtePickerTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 223, 30));
        getContentPane().add(dtePickerFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 210, 30));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel6.setText("To :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 40, 30));

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        jLabel8.setText("From :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 70, 30));

        btnTelephone.setBackground(new java.awt.Color(51, 51, 51));
        btnTelephone.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnTelephone.setForeground(new java.awt.Color(255, 255, 255));
        btnTelephone.setText("Telephone Summary");
        btnTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelephoneActionPerformed(evt);
            }
        });
        getContentPane().add(btnTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 190, 30));

        btnChef.setBackground(new java.awt.Color(51, 51, 51));
        btnChef.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnChef.setForeground(new java.awt.Color(255, 255, 255));
        btnChef.setText("Chef Summary");
        btnChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChefActionPerformed(evt);
            }
        });
        getContentPane().add(btnChef, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 150, 30));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtReportArea.setEditable(false);
        txtReportArea.setColumns(20);
        txtReportArea.setRows(5);
        jScrollPane1.setViewportView(txtReportArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 390, 240));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reports");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 50));

        btnPrint.setText("Print Reports");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelephoneActionPerformed
        try {
            Connection con = DBConnection.DBConnection.getnstance().getConnection();
            PreparedStatement ps = con.prepareStatement("SELECT tid,custName,cusContact,qty FROM OrderDetails WHERE  transDate BETWEEN ? AND ?");
            ps.setObject(1, converDate(dtePickerFrom.getDate()));
            ps.setObject(2, converDate(dtePickerTo.getDate()));
            ResultSet rs = ps.executeQuery();
            
        txtReportArea.setText("***************************************************************************\n");
        txtReportArea.setText(txtReportArea.getText() + "                                    Telephone Operator Summary \n");
        txtReportArea.setText(txtReportArea.getText() + "                                              "+LocalDate.now().toString()+"\n");
        txtReportArea.setText(txtReportArea.getText() + "***************************************************************************\n");

            while (rs.next()) {
                txtReportArea.setText(txtReportArea.getText() + "Telephone Operator : " + rs.getString(1) + "\n");
                txtReportArea.setText(txtReportArea.getText() + "Customer Contact : " + rs.getString(2) + "\n");
                txtReportArea.setText(txtReportArea.getText() + "Customer Name: " + rs.getString(3) + "\n");
                txtReportArea.setText(txtReportArea.getText() + "Order Quantity: " + rs.getInt(4) + "\n");
                txtReportArea.setText(txtReportArea.getText() + "***************************************************************************\n\n");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTelephoneActionPerformed

    private void btnChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChefActionPerformed
        try {
            Connection con = DBConnection.DBConnection.getnstance().getConnection();
            PreparedStatement ps = con.prepareStatement("SELECT chefId,COUNT(chefId),SUM(qty),SUM(timeTaken) from OrderDetails WHERE transDate BETWEEN ? AND ? GROUP BY chefId");
            ps.setObject(1, converDate(dtePickerFrom.getDate()));
            ps.setObject(2, converDate(dtePickerTo.getDate()));
            ResultSet rs = ps.executeQuery();
            
            txtReportArea.setText("***************************************************************************\n");
            txtReportArea.setText(txtReportArea.getText() + "                                         Report Chef Summary  \n");
            txtReportArea.setText(txtReportArea.getText() + "                                                "+LocalDate.now().toString()+"\n");
            txtReportArea.setText(txtReportArea.getText() + "***************************************************************************\n");

            while (rs.next()) {
                txtReportArea.setText(txtReportArea.getText() + "Chef ID : " + rs.getString(1) + "\n");
                txtReportArea.setText(txtReportArea.getText() + "No of Orders : " + rs.getInt(2) + "\n");
                txtReportArea.setText(txtReportArea.getText() + "Quantity : " + rs.getInt(3) + "\n");
                int mins=rs.getInt(4);
                int totalHours=mins/60;
                int totalMins=mins%60;
                txtReportArea.setText(txtReportArea.getText() + "Total Time Spend on the orders : " + totalHours+" . "+totalMins+" hrs\n\n");
                txtReportArea.setText(txtReportArea.getText() + "----------------------------------------------------------------------------------------------------\n");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChefActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
       
        try {
            txtReportArea.print();
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(rootPane, "Try Again..!");
        }
        
        
    }//GEN-LAST:event_btnPrintActionPerformed

    private String converDate(Date date) {
        DateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        return dt.format(date);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChef;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnTelephone;
    private org.jdesktop.swingx.JXDatePicker dtePickerFrom;
    private org.jdesktop.swingx.JXDatePicker dtePickerTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtReportArea;
    // End of variables declaration//GEN-END:variables
}
